language: ruby
services: postgresql
rvm:
- 1.9.3
- rbx-19mode
before_script:
- psql -c 'create database codeflash_test;' -U postgres
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake test
